const FeatureId = {
  MIN: 1,
  WEBSITES: 1,
  OWASP_SIGNATURE_WAF: 2,
  FREE_WILDCARD_CERTS: 3,
  REQUESTS: 4,
  DATA_RETENTION: 5,
  MACHINE_LEARNING_WAF: 6,
  CUSTOM_CERTS_UPLOAD: 7,
  CUSTOM_WAF_RULES: 8,
  CUSTOM_BLOCK_PAGE: 9,
  TEAM_MANAGEMENT: 10,
  ROLE_BASED_ACCESS_CONTROL: 11,
  RATE_LIMIT_RULE: 12,
  ADVANCED_FEATURES_IN_RATE_LIMIT_RULE: 13,
  LOG_REQUEST_PAYLOAD: 14,
  SENSEDEFENCE_SIGNATURE_WAF: 15,
  B2B_SAML: 16,
  BOT_MANAGEMENT: 17,
  MAX: 17,
};

const FeatureDataType = {
  BOOLEAN: 0,
  NUMBER: 1,
};

module.exports = { FeatureId, FeatureDataType };
